name: kedro

on:
  push

    
jobs:
  kedro:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Kedro
      uses: WaylonWalker/kedro-action@develop
      with:
        GITHUB_PAT: ${{ secrets.REPO_ONLY_PAT }}
#         verbose: true

