name: kedro

# on:
#   push:
#     branches:
#       - master

on:
  watch:
    types: [ started ]
    
jobs:
  kedro:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Kedro
      uses: WaylonWalker/kedro-action@develop
      with:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        verbose: true

