name: kedro

on:
  push:
    branches:
      - master

jobs:
  kedro:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Kedro
      uses: WaylonWalker/kedro-action@0.0.6
      with:
        python_version: '3.7.0'
